import { spawn, type ChildProcess } from "node:child_process";
import { readFileSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";
import {
  createPublicClient,
  createWalletClient,
  defineChain,
  http,
  type Abi,
  type Address,
  type Hex,
} from "viem";
import { privateKeyToAccount } from "viem/accounts";

/**
 * End-to-end harness: spawns a local Anvil (X Layer-compatible EVM), deploys the
 * real Talos contracts (Poseidon(2), MockERC20, TalosPool, the generated Groth16
 * verifiers + adapters), and mints test tokens. Everything downstream uses the real
 * cryptography — no mocks.
 */

const REPO_ROOT = join(process.cwd(), "..", "..");
const OUT = join(REPO_ROOT, "contracts", "out");
const FIXTURES = join(REPO_ROOT, "contracts", "test", "fixtures");

// Anvil default account #0.
export const ANVIL_PK = "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80" as Hex;
export const CHAIN_ID = 31337;

function anvilPath(): string {
  return process.env.ANVIL_PATH ?? join(homedir(), ".foundry", "bin", process.platform === "win32" ? "anvil.exe" : "anvil");
}

function artifact(file: string, contract: string): { abi: Abi; bytecode: Hex } {
  const json = JSON.parse(readFileSync(join(OUT, file, `${contract}.json`), "utf8"));
  return { abi: json.abi as Abi, bytecode: json.bytecode.object as Hex };
}

export interface Deployment {
  rpcUrl: string;
  pool: Address;
  asset: Address;
  hasher: Address;
  owner: Address;
  stop: () => void;
}

export async function startAnvil(port: number): Promise<ChildProcess> {
  const proc = spawn(anvilPath(), ["--port", String(port), "--chain-id", String(CHAIN_ID), "--silent"], {
    stdio: "ignore",
  });
  const rpcUrl = `http://127.0.0.1:${port}`;
  // Wait until responsive.
  for (let i = 0; i < 100; i++) {
    try {
      const res = await fetch(rpcUrl, {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ jsonrpc: "2.0", id: 1, method: "eth_blockNumber", params: [] }),
      });
      if (res.ok) return proc;
    } catch {
      /* not up yet */
    }
    await new Promise((r) => setTimeout(r, 100));
  }
  proc.kill();
  throw new Error("anvil did not start");
}

export async function deployAll(port: number, proc: ChildProcess): Promise<Deployment> {
  const rpcUrl = `http://127.0.0.1:${port}`;
  const chain = defineChain({
    id: CHAIN_ID,
    name: "anvil",
    nativeCurrency: { name: "ETH", symbol: "ETH", decimals: 18 },
    rpcUrls: { default: { http: [rpcUrl] } },
  });
  const account = privateKeyToAccount(ANVIL_PK);
  const pub = createPublicClient({ chain, transport: http(rpcUrl) });
  const wallet = createWalletClient({ account, chain, transport: http(rpcUrl) });

  const deploy = async (abi: Abi, bytecode: Hex, args: unknown[] = []): Promise<Address> => {
    const hash = await wallet.deployContract({ abi, bytecode, args, account, chain } as never);
    const receipt = await pub.waitForTransactionReceipt({ hash });
    if (!receipt.contractAddress) throw new Error("deploy failed");
    return receipt.contractAddress;
  };
  const write = async (address: Address, abi: Abi, functionName: string, args: unknown[]): Promise<void> => {
    const { request } = await pub.simulateContract({ address, abi, functionName, args, account });
    const hash = await wallet.writeContract(request);
    await pub.waitForTransactionReceipt({ hash });
  };

  // Poseidon(2) from generated bytecode (no constructor).
  const poseidonBytecode = JSON.parse(readFileSync(join(FIXTURES, "poseidon2.json"), "utf8")).bytecode as Hex;
  const poseidonHash = await wallet.sendTransaction({ data: poseidonBytecode, account, chain });
  const poseidonReceipt = await pub.waitForTransactionReceipt({ hash: poseidonHash });
  const hasher = poseidonReceipt.contractAddress!;

  const mock = artifact("MockERC20.sol", "MockERC20");
  const asset = await deploy(mock.abi, mock.bytecode);

  const poolArt = artifact("TalosPool.sol", "TalosPool");
  const pool = await deploy(poolArt.abi, poolArt.bytecode, [asset, hasher, account.address]);

  const adapter = artifact("TalosVerifier.sol", "TalosVerifier");
  const verifiers: Array<[string, string, number, number]> = [
    ["TransferVerifier", "TransferVerifier", 4, 0],
    ["SplitVerifier", "SplitVerifier", 4, 1],
    ["MergeVerifier", "MergeVerifier", 4, 2],
    ["WithdrawVerifier", "WithdrawVerifier", 5, 3],
  ];
  for (const [file, name, n, op] of verifiers) {
    const gen = artifact(`${file}.sol`, name);
    const genAddr = await deploy(gen.abi, gen.bytecode);
    const adapterAddr = await deploy(adapter.abi, adapter.bytecode, [genAddr, BigInt(n)]);
    await write(pool, poolArt.abi, "setVerifier", [op, adapterAddr]);
  }

  // Fund the signer with test tokens.
  await write(asset, mock.abi, "mint", [account.address, 1_000_000n * 10n ** 6n]);

  return {
    rpcUrl,
    pool,
    asset,
    hasher,
    owner: account.address,
    stop: () => proc.kill(),
  };
}
