// SPDX-License-Identifier: MIT
pragma solidity 0.8.30;

import {Test} from "forge-std/Test.sol";
import {stdJson} from "forge-std/StdJson.sol";
import {IHasher} from "../src/interfaces/IHasher.sol";
import {TalosTypes} from "../src/TalosTypes.sol";

/**
 * @title PoseidonVectorsTest
 * @notice Proves the on-chain Poseidon(2) contract (deployed from the circomlibjs
 *         bytecode) reproduces the SAME hashes as the off-chain builder and the
 *         circom circuits, using the frozen vectors in circuits/test-vectors.
 * @dev This is the Poseidon-compatibility guardrail (Phase 3 §12). If the on-chain
 *      hasher and the vectors ever disagree, these tests fail — STOP, do not "fix"
 *      by editing values. commitment/nullifier (arity 5 / 2) are consumed as
 *      fixtures; their cross-implementation agreement is additionally proven by the
 *      end-to-end proofs, which are built from these same hashes and verify on-chain.
 */
contract PoseidonVectorsTest is Test {
    using stdJson for string;

    IHasher internal hasher;
    string internal vec;

    function setUp() public {
        // Deploy the real Poseidon(2) contract from the generated bytecode.
        string memory pj = vm.readFile("test/fixtures/poseidon2.json");
        bytes memory code = pj.readBytes(".bytecode");
        address addr;
        assembly {
            addr := create(0, add(code, 0x20), mload(code))
        }
        require(addr != address(0), "poseidon deploy failed");
        hasher = IHasher(addr);

        vec = vm.readFile("../circuits/test-vectors/vectors.json");
    }

    function test_Poseidon2_MatchesVector() public view {
        uint256[] memory inputs = vec.readUintArray(".poseidon2.inputs");
        uint256 expected = vec.readUint(".poseidon2.output");
        assertEq(hasher.poseidon([inputs[0], inputs[1]]), expected, "poseidon2 mismatch");
    }

    function test_MerkleRoot_MatchesVector_ViaPoseidon() public view {
        // Recompute the root from leaf 0 and its authentication path using the
        // on-chain Poseidon(2), exactly as MerkleTreeLib / the circuit do.
        uint256 leaf = vec.readUint(".merkle.proofForLeaf0.leaf");
        uint256[] memory pe = vec.readUintArray(".merkle.proofForLeaf0.pathElements");
        uint256[] memory pi = vec.readUintArray(".merkle.proofForLeaf0.pathIndices");
        uint256 expectedRoot = vec.readUint(".merkle.root");

        uint256 cur = leaf;
        for (uint256 i = 0; i < pe.length; i++) {
            if (pi[i] == 0) {
                cur = hasher.poseidon([cur, pe[i]]);
            } else {
                cur = hasher.poseidon([pe[i], cur]);
            }
        }
        assertEq(cur, expectedRoot, "merkle root mismatch");
    }

    function test_Vectors_AreCanonicalFieldElements() public view {
        // commitment/nullifier vectors must be valid, nonzero BN254 field elements.
        uint256 commitment = vec.readUint(".commitment.output");
        uint256 nullifier = vec.readUint(".nullifier.output");
        assertTrue(commitment != 0 && commitment < TalosTypes.FIELD_SIZE, "commitment out of field");
        assertTrue(nullifier != 0 && nullifier < TalosTypes.FIELD_SIZE, "nullifier out of field");
    }
}
