// SPDX-License-Identifier: MIT
pragma solidity 0.8.30;

import {Test} from "forge-std/Test.sol";
import {stdJson} from "forge-std/StdJson.sol";
import {TalosPool} from "../src/TalosPool.sol";
import {TalosAssetRegistry} from "../src/TalosAssetRegistry.sol";
import {TalosVerifier} from "../src/TalosVerifier.sol";
import {ITalosVerifier} from "../src/interfaces/ITalosVerifier.sol";
import {ITalosAssetRegistry} from "../src/interfaces/ITalosAssetRegistry.sol";
import {IHasher} from "../src/interfaces/IHasher.sol";
import {TalosTypes} from "../src/TalosTypes.sol";
import {MockERC20} from "./mocks/MockERC20.sol";
import {MockVerifier} from "./mocks/MockVerifier.sol";
import {DepositVerifier} from "../src/verifiers/DepositVerifier.sol";
import {TransferVerifier} from "../src/verifiers/TransferVerifier.sol";
import {SplitVerifier} from "../src/verifiers/SplitVerifier.sol";
import {MergeVerifier} from "../src/verifiers/MergeVerifier.sol";
import {WithdrawVerifier} from "../src/verifiers/WithdrawVerifier.sol";
import {
    Talos__InvalidProof,
    Talos__InvalidRoot,
    Talos__NullifierAlreadySpent
} from "../src/TalosErrors.sol";

/**
 * @title TalosE2ETest
 * @notice The Phase 3 milestone: real Groth16 proofs — generated from private
 *         witnesses by snarkjs — are accepted by the generated Solidity verifiers
 *         through the {ITalosVerifier} boundary and drive real TalosPool state
 *         transitions. The Merkle tree uses the REAL circomlib Poseidon(2) contract,
 *         so on-chain roots match the roots the proofs were built against.
 * @dev No mock verifier and no mock hasher are used here. Fixtures are generated by
 *      `pnpm zk:fixtures` and contain only public data + proofs.
 */
contract TalosE2ETest is Test {
    using stdJson for string;

    TalosPool internal pool;
    MockERC20 internal token;
    IHasher internal hasher;

    address internal owner = address(this);

    function setUp() public {
        token = new MockERC20();
        hasher = IHasher(_deployPoseidon());
        TalosAssetRegistry registry = new TalosAssetRegistry(owner);
        registry.registerAsset(TalosTypes.ASSET_ID, address(token), false, "tUSDC", 6);
        pool = new TalosPool(ITalosAssetRegistry(address(registry)), hasher, owner);

        // Wire the REAL generated Groth16 verifiers behind the adapter, per op.
        pool.setVerifier(
            TalosTypes.Operation.Transfer,
            ITalosVerifier(address(new TalosVerifier(address(new TransferVerifier()), 4)))
        );
        pool.setVerifier(
            TalosTypes.Operation.Split,
            ITalosVerifier(address(new TalosVerifier(address(new SplitVerifier()), 4)))
        );
        pool.setVerifier(
            TalosTypes.Operation.Merge,
            ITalosVerifier(address(new TalosVerifier(address(new MergeVerifier()), 4)))
        );
        pool.setVerifier(
            TalosTypes.Operation.Withdraw,
            ITalosVerifier(address(new TalosVerifier(address(new WithdrawVerifier()), 5)))
        );
        // Tree-seeding deposits use a permissive Deposit verifier (seeding is not the unit
        // under test). test_E2E_Deposit swaps in the REAL DepositVerifier + a real proof.
        pool.setVerifier(
            TalosTypes.Operation.Deposit, ITalosVerifier(address(new MockVerifier(true)))
        );
    }

    /// @dev A zeroed proof for seeding deposits under the permissive Deposit verifier.
    ///      `p.data` is zero-initialized by default, so nothing to set.
    function _noProof() internal pure returns (TalosTypes.Proof memory p) {
        return p;
    }

    /*//////////////////////////////////////////////////////////////
                          POSEIDON DEPLOYMENT
    //////////////////////////////////////////////////////////////*/

    function _deployPoseidon() internal returns (address addr) {
        string memory json = vm.readFile("test/fixtures/poseidon2.json");
        bytes memory code = json.readBytes(".bytecode");
        assembly {
            addr := create(0, add(code, 0x20), mload(code))
        }
        require(addr != address(0), "poseidon deploy failed");
    }

    /*//////////////////////////////////////////////////////////////
                           FIXTURE HELPERS
    //////////////////////////////////////////////////////////////*/

    function _read(string memory op) internal view returns (string memory) {
        return vm.readFile(string.concat("test/fixtures/", op, ".json"));
    }

    function _proof(string memory json) internal pure returns (TalosTypes.Proof memory p) {
        uint256[] memory d = json.readUintArray(".proof");
        require(d.length == 24, "fixture proof must be 24 words");
        for (uint256 i = 0; i < 24; ++i) {
            p.data[i] = d[i];
        }
    }

    /// @dev Reproduce the on-chain Merkle state the proof was built against.
    function _applyDeposits(string memory json) internal {
        uint256[] memory commitments = json.readUintArray(".depositCommitments");
        uint256[] memory amounts = json.readUintArray(".depositAmounts");
        for (uint256 i = 0; i < commitments.length; i++) {
            token.mint(address(this), amounts[i]);
            token.approve(address(pool), amounts[i]);
            pool.deposit(_noProof(), TalosTypes.ASSET_ID, amounts[i], commitments[i]);
        }
    }

    /*//////////////////////////////////////////////////////////////
                       SCENARIO 1 — DEPOSIT
    //////////////////////////////////////////////////////////////*/

    function test_E2E_Deposit() public {
        string memory json = _read("deposit");
        uint256 assetId = json.readUint(".assetId");
        uint256 amount = json.readUint(".amount");
        uint256 commitment = json.readUint(".commitment");

        // B1: use the REAL generated DepositVerifier — the pool now verifies the binding
        // proof that (assetId, amount) match the value/asset committed in `commitment`.
        pool.setVerifier(
            TalosTypes.Operation.Deposit,
            ITalosVerifier(address(new TalosVerifier(address(new DepositVerifier()), 3)))
        );

        token.mint(address(this), amount);
        token.approve(address(pool), amount);
        pool.deposit(_proof(json), assetId, amount, commitment);

        assertTrue(pool.commitmentInserted(commitment), "commitment not inserted");
        assertEq(token.balanceOf(address(pool)), amount, "pool not funded");
    }

    /// @dev B1 negative: a real proof cannot be reused with a mismatched public `amount`
    ///      (which would let a depositor over-credit). The DepositVerifier rejects it.
    function test_E2E_Deposit_RejectsAmountMismatch() public {
        string memory json = _read("deposit");
        uint256 assetId = json.readUint(".assetId");
        uint256 amount = json.readUint(".amount");
        uint256 commitment = json.readUint(".commitment");

        pool.setVerifier(
            TalosTypes.Operation.Deposit,
            ITalosVerifier(address(new TalosVerifier(address(new DepositVerifier()), 3)))
        );
        token.mint(address(this), amount + 1);
        token.approve(address(pool), amount + 1);

        // Same proof, inflated public amount → signals no longer match the proof.
        vm.expectRevert(Talos__InvalidProof.selector);
        pool.deposit(_proof(json), assetId, amount + 1, commitment);
    }

    /*//////////////////////////////////////////////////////////////
                        SCENARIO 2 — SPLIT
    //////////////////////////////////////////////////////////////*/

    function test_E2E_Split() public {
        string memory json = _read("split");
        _applyDeposits(json);

        uint256 root = json.readUint(".root");
        uint256 nullifier = json.readUint(".nullifier");
        uint256 out1 = json.readUint(".outCommitment1");
        uint256 out2 = json.readUint(".outCommitment2");
        assertEq(pool.getLastRoot(), root, "on-chain root != proof root");

        pool.split(_proof(json), root, nullifier, out1, out2);

        assertTrue(pool.isNullifierSpent(nullifier), "nullifier not consumed");
        assertTrue(
            pool.commitmentInserted(out1) && pool.commitmentInserted(out2), "outputs not inserted"
        );
    }

    /*//////////////////////////////////////////////////////////////
                        SCENARIO 3 — MERGE
    //////////////////////////////////////////////////////////////*/

    function test_E2E_Merge() public {
        string memory json = _read("merge");
        _applyDeposits(json);

        uint256 root = json.readUint(".root");
        uint256 n1 = json.readUint(".nullifier1");
        uint256 n2 = json.readUint(".nullifier2");
        uint256 outC = json.readUint(".outCommitment");
        assertEq(pool.getLastRoot(), root, "on-chain root != proof root");

        pool.merge(_proof(json), root, n1, n2, outC);

        assertTrue(
            pool.isNullifierSpent(n1) && pool.isNullifierSpent(n2), "nullifiers not consumed"
        );
        assertTrue(pool.commitmentInserted(outC), "output not inserted");
    }

    /*//////////////////////////////////////////////////////////////
                       SCENARIO 4 — TRANSFER
    //////////////////////////////////////////////////////////////*/

    function test_E2E_Transfer() public {
        string memory json = _read("transfer");
        _applyDeposits(json);

        uint256 root = json.readUint(".root");
        uint256 nullifier = json.readUint(".nullifier");
        uint256 out1 = json.readUint(".outCommitment1");
        uint256 out2 = json.readUint(".outCommitment2");

        pool.transfer(_proof(json), root, nullifier, out1, out2);

        assertTrue(pool.isNullifierSpent(nullifier), "nullifier not consumed");
        assertTrue(
            pool.commitmentInserted(out1) && pool.commitmentInserted(out2), "outputs not inserted"
        );
    }

    /*//////////////////////////////////////////////////////////////
                       SCENARIO 5 — WITHDRAW
    //////////////////////////////////////////////////////////////*/

    function test_E2E_Withdraw() public {
        string memory json = _read("withdraw");
        _applyDeposits(json);

        uint256 root = json.readUint(".root");
        uint256 nullifier = json.readUint(".nullifier");
        uint256 amount = json.readUint(".amount");
        address recipient = json.readAddress(".recipient");

        uint256 before = token.balanceOf(recipient);
        pool.withdraw(_proof(json), root, nullifier, amount, recipient, TalosTypes.ASSET_ID);

        assertEq(token.balanceOf(recipient) - before, amount, "recipient not paid");
        assertTrue(pool.isNullifierSpent(nullifier), "nullifier not consumed");
    }

    /*//////////////////////////////////////////////////////////////
                          NEGATIVE TESTS
    //////////////////////////////////////////////////////////////*/

    function test_E2E_RejectsModifiedProof() public {
        string memory json = _read("split");
        _applyDeposits(json);
        TalosTypes.Proof memory p = _proof(json);
        p.data[0] = p.data[0] ^ 1; // tamper one bit

        vm.expectRevert(Talos__InvalidProof.selector);
        pool.split(
            p,
            json.readUint(".root"),
            json.readUint(".nullifier"),
            json.readUint(".outCommitment1"),
            json.readUint(".outCommitment2")
        );
    }

    function test_E2E_RejectsModifiedPublicSignal() public {
        string memory json = _read("split");
        _applyDeposits(json);
        // Keep the valid proof but change a public input (nullifier); the pool feeds
        // the changed signal to the verifier, which rejects it.
        uint256 tamperedNullifier = json.readUint(".nullifier") + 1;

        vm.expectRevert(Talos__InvalidProof.selector);
        pool.split(
            _proof(json),
            json.readUint(".root"),
            tamperedNullifier,
            json.readUint(".outCommitment1"),
            json.readUint(".outCommitment2")
        );
    }

    function test_E2E_RejectsUnknownRoot() public {
        string memory json = _read("split");
        _applyDeposits(json);

        vm.expectRevert(Talos__InvalidRoot.selector);
        pool.split(
            _proof(json),
            json.readUint(".root") + 1,
            json.readUint(".nullifier"),
            json.readUint(".outCommitment1"),
            json.readUint(".outCommitment2")
        );
    }

    function test_E2E_RejectsNullifierReplay() public {
        string memory json = _read("withdraw");
        _applyDeposits(json);
        uint256 root = json.readUint(".root");
        uint256 nullifier = json.readUint(".nullifier");
        uint256 amount = json.readUint(".amount");
        address recipient = json.readAddress(".recipient");

        pool.withdraw(_proof(json), root, nullifier, amount, recipient, TalosTypes.ASSET_ID);

        vm.expectRevert(Talos__NullifierAlreadySpent.selector);
        pool.withdraw(_proof(json), root, nullifier, amount, recipient, TalosTypes.ASSET_ID);
    }
}
