// Groth16 trusted setup + verifier generation for all Talos circuits.
//
// DEVELOPMENT CEREMONY ONLY. The Powers of Tau and phase-2 contributions use fixed,
// published entropy strings and a single contributor. This is reproducible and fine
// for a hackathon/testnet MVP, but it is NOT a production-secure ceremony: anyone can
// reproduce the toxic waste. This is stated in docs/protocol/zk-system.md.
//
// Pipeline per circuit: r1cs + ptau -> zkey (phase2) -> vkey.json + Solidity verifier.

import { spawnSync } from "child_process";
import fs from "fs";
import path from "path";
import { ROOT, poseidonT3Artifact, require_ } from "./lib.mjs";

// snarkjs restricts package exports, so locate its CLI relative to the main entry.
const SNARKJS = path.join(path.dirname(require_.resolve("snarkjs")), "cli.cjs");
const POWER = 15; // 2^15 = 32768 >= max circuit constraints (merge ~12k)
const PTAU_DIR = path.join(ROOT, "circuits", "build", "ptau");
const PTAU_FINAL = path.join(PTAU_DIR, `pot${POWER}_final.ptau`);
const VERIFIER_DIR = path.join(ROOT, "contracts", "src", "verifiers");
const FIXTURE_DIR = path.join(ROOT, "contracts", "test", "fixtures");

// circuit -> number of public signals (frozen public-input counts)
const CIRCUITS = {
  deposit: 3,
  transfer: 4,
  split: 4,
  merge: 4,
  withdraw: 5,
};

function snarkjs(args) {
  const r = spawnSync(process.execPath, [SNARKJS, ...args], { stdio: "inherit" });
  if (r.status !== 0) throw new Error(`snarkjs ${args.join(" ")} failed (${r.status})`);
}

function ensurePtau() {
  if (fs.existsSync(PTAU_FINAL)) {
    console.log("ptau already present:", path.relative(ROOT, PTAU_FINAL));
    return;
  }
  fs.mkdirSync(PTAU_DIR, { recursive: true });
  const p0 = path.join(PTAU_DIR, `pot${POWER}_0000.ptau`);
  const p1 = path.join(PTAU_DIR, `pot${POWER}_0001.ptau`);
  console.log("\n=== Powers of Tau (bn128, power", POWER, ") — DEV CEREMONY ===");
  snarkjs(["powersoftau", "new", "bn128", String(POWER), p0, "-v"]);
  snarkjs([
    "powersoftau",
    "contribute",
    p0,
    p1,
    "--name=talos-dev-contribution-1",
    "-e=talos development entropy — NOT production",
    "-v",
  ]);
  snarkjs(["powersoftau", "prepare", "phase2", p1, PTAU_FINAL, "-v"]);
  fs.rmSync(p0, { force: true });
  fs.rmSync(p1, { force: true });
}

function setupCircuit(name) {
  const buildDir = path.join(ROOT, "circuits", "build", name);
  const r1cs = path.join(buildDir, `${name}.r1cs`);
  const zkey0 = path.join(buildDir, `${name}_0000.zkey`);
  const zkeyFinal = path.join(buildDir, `${name}_final.zkey`);
  const vkey = path.join(buildDir, "verification_key.json");

  console.log(`\n=== groth16 setup: ${name} ===`);
  snarkjs(["groth16", "setup", r1cs, PTAU_FINAL, zkey0]);
  snarkjs([
    "zkey",
    "contribute",
    zkey0,
    zkeyFinal,
    "--name=talos-dev-phase2-1",
    "-e=talos phase2 entropy — NOT production",
    "-v",
  ]);
  snarkjs(["zkey", "export", "verificationkey", zkeyFinal, vkey]);
  fs.rmSync(zkey0, { force: true });

  // Solidity verifier: generate, then rename the contract per circuit.
  fs.mkdirSync(VERIFIER_DIR, { recursive: true });
  const solName = name.charAt(0).toUpperCase() + name.slice(1) + "Verifier";
  const solPath = path.join(VERIFIER_DIR, `${solName}.sol`);
  snarkjs(["zkey", "export", "solidityverifier", zkeyFinal, solPath]);
  let sol = fs.readFileSync(solPath, "utf8");
  sol = sol.replace(/contract\s+Groth16Verifier\b/, `contract ${solName}`);
  sol =
    "// SPDX-License-Identifier: GPL-3.0\n" +
    "// GENERATED by snarkjs from circuits/" +
    name +
    "/" +
    name +
    ".circom — DO NOT EDIT.\n" +
    "// Regenerate with `pnpm zk:setup`. This is the real Groth16 verifier.\n" +
    sol.replace(/^\/\/ SPDX-License-Identifier:.*\n/m, "");
  fs.writeFileSync(solPath, sol);
  console.log("wrote", path.relative(ROOT, solPath));
}

function writePoseidonArtifact() {
  fs.mkdirSync(FIXTURE_DIR, { recursive: true });
  const { bytecode, abi } = poseidonT3Artifact();
  const bc = bytecode.startsWith("0x") ? bytecode : "0x" + bytecode;
  const out = path.join(FIXTURE_DIR, "poseidon2.json");
  fs.writeFileSync(out, JSON.stringify({ bytecode: bc, abi }, null, 2) + "\n");
  console.log("wrote", path.relative(ROOT, out), `(bytecode ${bc.length} chars)`);
}

function main() {
  ensurePtau();
  for (const name of Object.keys(CIRCUITS)) setupCircuit(name);
  writePoseidonArtifact();
  fs.writeFileSync(
    path.join(FIXTURE_DIR, "circuits.json"),
    JSON.stringify({ publicSignalCounts: CIRCUITS }, null, 2) + "\n"
  );
  console.log("\nGroth16 setup complete.");
}

main();
