// PLONK trusted setup + verifier generation for all Talos circuits.
//
// PRODUCTION-GRADE SETUP. PLONK uses a *universal, updatable* structured reference
// string (SRS) — the Powers of Tau — and requires NO per-circuit "phase 2" ceremony
// and NO per-circuit toxic waste. We anchor to the real **Perpetual Powers of Tau**
// (contribution #80), a public multi-party ceremony with 80+ independent contributors
// mirrored by the Ethereum Foundation's Privacy & Scaling Explorations (PSE). Because
// the SRS is sound as long as ANY ONE of those 80+ contributors destroyed their
// secret, this closes the B2 trusted-setup blocker without us running a bespoke
// ceremony. See docs/protocol/zk-system.md and the generated ceremony-transcript.json.
//
// Pipeline per circuit: r1cs + universal ptau -> plonk zkey -> vkey.json + Solidity verifier.
// The ptau is a BUILD-TIME input only; runtime needs only the per-circuit zkey + vkey.

import { spawnSync } from "child_process";
import crypto from "crypto";
import fs from "fs";
import path from "path";
import { ROOT, poseidonT3Artifact, require_ } from "./lib.mjs";

// snarkjs restricts package exports, so locate its CLI relative to the main entry.
const SNARKJS = path.join(path.dirname(require_.resolve("snarkjs")), "cli.cjs");

// --- Perpetual Powers of Tau (universal SRS) ---
// Power 16 = 2^16 = 65536 gates >= largest circuit (merge ~30.6k PLONK constraints).
// PLONK needs one power more than the equivalent Groth16 setup for its quotient poly.
const POWER = 16;
const PTAU_DIR = path.join(ROOT, "circuits", "build", "ptau");
const PTAU = path.join(PTAU_DIR, `ppot_0080_${POWER}.ptau`);
const PTAU_URL = `https://pse-trusted-setup-ppot.s3.eu-central-1.amazonaws.com/pot28_0080/ppot_0080_${POWER}.ptau`;
// SHA-256 of ppot_0080_16.ptau as published by PSE (pinned; verified on download).
const PTAU_SHA256 = "ed3622a7c79b0b49aadd134ebbc5b77df8c8c59bccebdfd0d9bf2c1a51561cf9";
const PTAU_CONTRIBUTION = 80;

const VERIFIER_DIR = path.join(ROOT, "contracts", "src", "verifiers");
const FIXTURE_DIR = path.join(ROOT, "contracts", "test", "fixtures");
const TRANSCRIPT = path.join(ROOT, "circuits", "build", "ceremony-transcript.json");

// circuit -> number of public signals (frozen public-input counts)
const CIRCUITS = {
  deposit: 3,
  transfer: 4,
  split: 4,
  merge: 4,
  withdraw: 5,
};

function snarkjs(args) {
  const r = spawnSync(process.execPath, [SNARKJS, ...args], { stdio: "inherit" });
  if (r.status !== 0) throw new Error(`snarkjs ${args.join(" ")} failed (${r.status})`);
}

function sha256(file) {
  return crypto.createHash("sha256").update(fs.readFileSync(file)).digest("hex");
}

async function download(url, dest) {
  console.log("downloading", url);
  const res = await fetch(url);
  if (!res.ok) throw new Error(`download failed: ${res.status} ${res.statusText}`);
  const buf = Buffer.from(await res.arrayBuffer());
  fs.writeFileSync(dest, buf);
}

async function ensurePtau() {
  fs.mkdirSync(PTAU_DIR, { recursive: true });
  if (!fs.existsSync(PTAU)) {
    console.log("\n=== Perpetual Powers of Tau (#%d, power %d) — universal SRS ===", PTAU_CONTRIBUTION, POWER);
    await download(PTAU_URL, PTAU);
  }
  const got = sha256(PTAU);
  if (got !== PTAU_SHA256) {
    throw new Error(
      `ptau SHA-256 mismatch!\n  expected ${PTAU_SHA256}\n  got      ${got}\n` +
        `Refusing to build a verifier from an unverified SRS. Delete the file and retry.`,
    );
  }
  console.log("ptau present + SHA-256 verified:", path.relative(ROOT, PTAU), got);
  // Cryptographic chain verification (slow) is opt-in via SETUP_VERIFY_PTAU=1.
  if (process.env["SETUP_VERIFY_PTAU"] === "1") {
    console.log("verifying powers-of-tau ceremony chain (slow)...");
    snarkjs(["powersoftau", "verify", PTAU]);
  }
}

function setupCircuit(name) {
  const buildDir = path.join(ROOT, "circuits", "build", name);
  const r1cs = path.join(buildDir, `${name}.r1cs`);
  const zkeyFinal = path.join(buildDir, `${name}_final.zkey`);
  const vkey = path.join(buildDir, "verification_key.json");

  console.log(`\n=== plonk setup: ${name} ===`);
  // PLONK setup is deterministic given (r1cs, ptau): no per-circuit contribution.
  snarkjs(["plonk", "setup", r1cs, PTAU, zkeyFinal]);
  snarkjs(["zkey", "export", "verificationkey", zkeyFinal, vkey]);

  // Solidity verifier: generate, then rename the contract per circuit.
  fs.mkdirSync(VERIFIER_DIR, { recursive: true });
  const solName = name.charAt(0).toUpperCase() + name.slice(1) + "Verifier";
  const solPath = path.join(VERIFIER_DIR, `${solName}.sol`);
  snarkjs(["zkey", "export", "solidityverifier", zkeyFinal, solPath]);
  let sol = fs.readFileSync(solPath, "utf8");
  sol = sol.replace(/contract\s+PlonkVerifier\b/, `contract ${solName}`);
  sol =
    "// SPDX-License-Identifier: GPL-3.0\n" +
    "// GENERATED by snarkjs (PLONK) from circuits/" +
    name +
    "/" +
    name +
    ".circom — DO NOT EDIT.\n" +
    "// Regenerate with `pnpm zk:setup`. Real PLONK verifier over the Perpetual\n" +
    "// Powers of Tau universal SRS (see circuits/build/ceremony-transcript.json).\n" +
    sol.replace(/^\/\/ SPDX-License-Identifier:.*\n/m, "");
  fs.writeFileSync(solPath, sol);
  console.log("wrote", path.relative(ROOT, solPath));

  return { zkeySha256: sha256(zkeyFinal), vkeySha256: sha256(vkey), solSha256: sha256(solPath) };
}

function writePoseidonArtifact() {
  fs.mkdirSync(FIXTURE_DIR, { recursive: true });
  const { bytecode, abi } = poseidonT3Artifact();
  const bc = bytecode.startsWith("0x") ? bytecode : "0x" + bytecode;
  const out = path.join(FIXTURE_DIR, "poseidon2.json");
  fs.writeFileSync(out, JSON.stringify({ bytecode: bc, abi }, null, 2) + "\n");
  console.log("wrote", path.relative(ROOT, out), `(bytecode ${bc.length} chars)`);
}

async function main() {
  await ensurePtau();

  const circuits = {};
  for (const [name, signals] of Object.entries(CIRCUITS)) {
    circuits[name] = { publicSignals: signals, ...setupCircuit(name) };
  }

  writePoseidonArtifact();
  fs.writeFileSync(
    path.join(FIXTURE_DIR, "circuits.json"),
    JSON.stringify({ publicSignalCounts: CIRCUITS }, null, 2) + "\n",
  );

  // Verifiable ceremony transcript: anyone can re-derive these zkeys from the same
  // r1cs + the same public ptau and check the hashes match, then verify the ptau's
  // own contribution chain with `snarkjs powersoftau verify`.
  const transcript = {
    protocol: "plonk",
    curve: "bn128",
    setup: "universal (no per-circuit phase-2 ceremony; no per-circuit toxic waste)",
    srs: {
      name: "Perpetual Powers of Tau",
      contribution: PTAU_CONTRIBUTION,
      power: POWER,
      maxConstraints: 2 ** POWER,
      source: PTAU_URL,
      mirror: "Ethereum Foundation — Privacy & Scaling Explorations (PSE)",
      file: path.relative(ROOT, PTAU),
      sha256: PTAU_SHA256,
      soundness: "sound iff >=1 of the 80+ independent PPOT contributors destroyed their secret",
      verifyCommand: "snarkjs powersoftau verify circuits/build/ptau/ppot_0080_16.ptau",
    },
    circuits,
    generatedAt: new Date().toISOString(),
  };
  fs.writeFileSync(TRANSCRIPT, JSON.stringify(transcript, null, 2) + "\n");
  console.log("wrote", path.relative(ROOT, TRANSCRIPT));

  console.log("\nPLONK setup complete (universal SRS: Perpetual Powers of Tau #%d).", PTAU_CONTRIBUTION);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
